// src/seedData.js
// Run this once via the Admin dashboard to populate Firestore
// Or use: node scripts/seed.js

export const ROLES = [
  { id: 'chiller', name: 'Chiller', password: 'chiller2024', color: '#3b82f6' },
  { id: 'freezer', name: 'Freezer', password: 'freezer2024', color: '#06b6d4' },
  { id: 'dry', name: 'Dry', password: 'dry2024', color: '#f59e0b' },
  { id: 'veg', name: 'Veg', password: 'veg2024', color: '#22c55e' },
  { id: 'receiving', name: 'Receiving', password: 'receiving2024', color: '#8b5cf6' },
  { id: 'dispatch', name: 'Dispatch', password: 'dispatch2024', color: '#ef4444' },
  { id: 'batteries', name: 'Batteries', password: 'batteries2024', color: '#f97316' },
  { id: 'assets_lead', name: 'Assets Lead', password: 'assets2024', color: '#84cc16' },
  { id: 'night_shift_lead', name: 'Night Shift Lead', password: 'nightshift2024', color: '#6366f1' },
  { id: 'put_away_supervisor', name: 'Put Away Supervisor', password: 'putaway2024', color: '#14b8a6' },
  { id: 'receiving_supervisor', name: 'Receiving Supervisor', password: 'recsup2024', color: '#ec4899' },
  { id: 'packing_lead', name: 'Packing Lead', password: 'packing2024', color: '#78716c' },
  { id: 'logistics_lead', name: 'Logistics Lead', password: 'logistics2024', color: '#0ea5e9' },
  { id: 'warehouse_lead', name: 'Warehouse Lead', password: 'warehouse2024', color: '#a855f7' },
];

export const ADMIN_PASSWORD = 'admin@ops2024';

export const CHECKLIST_ITEMS = {
  dispatch: [
    "Today's riders called in 30 minutes before shift start",
    "Expected order volume for tomorrow reviewed and recorded",
    "Riders required for tomorrow calculated",
    "Riders available for tomorrow confirmed",
    "Rider deficit/surplus identified",
    "Any rider deficit escalated to supervisor/manager",
    "Riders for tomorrow's shift called and confirmed",
    "End-of-day sweep completed",
    "End-of-day performance snapshot shared",
  ],
  assets_lead: [
    "Batteries at charging station checked at end of day - ≥ 30 batteries",
    "R&M tracker updated",
    "Fuel tracker updated",
    "All bike and vehicle GPS trackers working",
    "Bikes issued to per-order riders returned",
    "Bike condition inspection completed (condition, mechanical, hygiene)",
    "Vehicle condition inspection completed (condition, mechanical, hygiene)",
    "Battery reconciliation completed",
    "Vehicle reconciliation completed",
    "Bike reconciliation completed",
    "Bike and vehicle insurance validity checked",
    "Driver license validity checked",
  ],
  batteries: [
    "Battery count physically verified at start of shift",
    "All batteries reconciled against issue and return records",
    "Any batteries missing identified and recorded",
    "Missing battery IDs / quantities escalated",
    "Faulty batteries identified and isolated",
    "Faulty battery IDs / quantities recorded",
    "Batteries currently on charge counted and recorded",
    "Batteries currently out in use counted and recorded",
    "Batteries handed over to users/operators recorded",
    "Handover recipient name confirmed and logged",
    "Returned batteries checked for condition",
    "Charging area clean and organized",
    "Unsafe / damaged charging points reported",
    "End-of-shift battery summary completed",
    "Handover to next shift completed",
  ],
  chiller: [
    "Previous shift backlog reviewed",
    "All received products scheduled for put away reviewed",
    "Replenishment completed 7:00 AM",
    "Replenishment completed 10:00 AM",
    "Replenishment completed 12:00 PM",
    "Replenishment completed 3:00 PM",
    "Cycle count completed for assigned SKUs - 180",
    "Expiry checks completed for all assigned stock",
    "Short-dated stock identified and isolated",
    "Quality grading completed for all required products",
    "FEFO followed during replenishment and put away",
    "Temperature check completed and recorded 7:00 AM",
    "Temperature check completed and recorded 10:00 AM",
    "Temperature check completed and recorded 1:00 PM",
    "Temperature check completed and recorded 3:00 PM",
    "Humidifier check completed and recorded 7:00 AM",
    "Humidifier check completed and recorded 10:00 AM",
    "Humidifier check completed and recorded 1:00 PM",
    "Humidifier check completed and recorded 3:00 PM",
    "Aisles clear and no stock stored on floor - Hourly",
    "Damaged/leaking stock isolated and reported",
    "All received products put away by end of shift",
    "Pending put away quantity recorded",
    "Shift handover completed for pending issues",
  ],
  freezer: [
    "Previous shift backlog reviewed",
    "All received products scheduled for put away reviewed",
    "Replenishment completed 7:00 AM",
    "Replenishment completed 10:00 AM",
    "Replenishment completed 12:00 PM",
    "Replenishment completed 3:00 PM",
    "Cycle count completed for 180 SKUs",
    "Expiry checks completed for all assigned stock",
    "Frozen stock handled within required exposure limits",
    "Door discipline maintained during operations",
    "Ice build-up / obstruction checked and reported",
    "Temperature check completed and recorded 7:00 AM",
    "Temperature check completed and recorded 10:00 AM",
    "Cycle count completed for assigned SKUs - 180",
    "Temperature check completed and recorded 1:00 PM",
    "Temperature check completed and recorded 3:00 PM",
    "Aisles clear and no stock stored on floor",
    "Damaged packaging / thaw risk stock isolated",
    "PPE compliance checked",
    "All received products put away by end of shift",
    "Pending put away quantity recorded",
    "Shift handover completed for pending issues",
  ],
  dry: [
    "Previous shift backlog reviewed",
    "All received products scheduled for put away reviewed",
    "Replenishment completed 7:00 AM",
    "Replenishment completed 10:00 AM",
    "Replenishment completed 12:00 PM",
    "Replenishment completed 3:00 PM",
    "Cycle count completed for assigned SKUs -300",
    "Expiry checks completed for all assigned stock",
    "Fast-moving items replenished first",
    "Safe stacking maintained in all locations",
    "Overstock not blocking pick faces",
    "Aisles clear and no stock stored on floor",
    "Damaged cartons / poor packaging isolated and reported",
    "Housekeeping standard maintained",
    "All received products put away by end of shift",
    "Pending put away quantity recorded",
    "Shift handover completed for pending issues",
  ],
  veg: [
    "Previous shift backlog reviewed",
    "All received products scheduled for put away reviewed",
    "Replenishment completed 7:00 AM",
    "Replenishment completed 10:00 AM",
    "Replenishment completed 12:00 PM",
    "Replenishment completed 3:00 PM",
    "Cycle count completed for assigned locations/SKUs",
    "Expiry checks completed for all assigned stock",
    "Short-dated stock identified and isolated",
    "Quality grading completed for all required products",
    "FEFO followed during replenishment and put away",
    "Cycle count completed for assigned SKUs - 60",
    "Temperature check completed and recorded 7:00 AM",
    "Temperature check completed and recorded 10:00 AM",
    "Temperature check completed and recorded 1:00 PM",
    "Temperature check completed and recorded 3:00 PM",
    "Humidifier check completed and recorded 7:00 AM",
    "Humidifier check completed and recorded 10:00 AM",
    "Humidifier check completed and recorded 1:00 PM",
    "Humidifier check completed and recorded 3:00 PM",
    "Aisles clear and no stock stored on floor - Hourly",
    "Damaged/leaking stock isolated and reported",
    "All received products put away by end of shift",
    "Pending put away quantity recorded",
    "Shift handover completed for pending issues",
  ],
  receiving: [
    "Expected deliveries reviewed",
    "All items physically received today also received in the system",
    "Any unbooked receipts identified and escalated",
    "Wrong posting cases identified",
    "Wrong posting cases resolved",
    "FPOs received reconciled",
    "Receipt discrepancies recorded and escalated",
    "Damaged / short / excess receipts recorded",
    "Handover completed for unresolved receipt issues",
  ],
  receiving_supervisor: [
    "Expected deliveries reviewed",
    "All items physically received today also received in the system",
    "Any unbooked receipts identified and escalated",
    "Wrong posting cases identified",
    "Wrong posting cases resolved",
    "FPOs received reconciled",
    "Receipt discrepancies recorded and escalated",
    "Damaged / short / excess receipts recorded",
    "Handover completed for unresolved receipt issues",
  ],
  packing_lead: [
    "Conduct the daily huddle with pickers and packers - 5:00 AM",
    "Allocate team members based on order volume and priority - 5:00 AM",
    "Allocate team members based on order volume and priority - 12:00 PM",
    "Allocate team members based on order volume and priority - 2:00 PM",
    "Allocate team members based on order volume and priority - 4:00 PM",
    "Verify picking accuracy - Randomly sample 15 orders",
    "Check packing materials availability",
    "Oversee packing of fragile, chilled, frozen, and special items - Sample 15 orders",
    "Confirm all labeling is correct (fragile, chilled, customer notes) - Sample 15 orders",
    "Ensure cleanliness and hygiene at all packing stations - Check every hour",
    "Monitor packing speed and accuracy, address errors immediately",
    "Conduct random quality checks on packed orders - Sample 15 orders",
    "Share customer complaints feedback with picking and packing team (4x daily)",
    "Share daily performance updates with picking and packing team - EOD",
    "Coordinate with Warehouse Lead on stock levels and replenishment - Morning & EOD",
    "Align with Dispatch Lead to ensure timely handover",
    "Ensure workflow supports on-time dispatch and end-of-day closure",
    "Plan resources and staffing for the next day",
    "Log any issues, incidents, or observations - EOD",
  ],
  logistics_lead: [
    "Dispatch screen is on and clearly displaying live performance",
    "Allocate team members based on order volume and priority - 7 AM",
    "Allocate team members based on order volume and priority - 11 AM",
    "Allocate team members based on order volume and priority - 3 PM",
    "Allocate team members based on order volume and priority - 7 PM",
    "Verify each rider meets uniform, PPE standards and tools of trade before shift start",
    "Check readiness of vehicles and motorbikes - Every Morning and EOD",
    "Ensure dispatch team is aligned with delivery priorities and order flow - Every 2 hours",
    "Monitor live delivery metrics and share performance updates every four hours",
    "Communicate delays, issues, or special customer instructions to CS team",
    "Resolve real-time delivery challenges or customer-impacting issues",
    "Track and record rider return times and any issues encountered",
    "Ensure all delivery orders are fully closed by EOD",
    "Plan resources and staffing for the next day",
    "Check that dispatchers daily checklists are completed and signed off",
    "Log daily issues, incidents, and improvement suggestions for follow-up",
  ],
  warehouse_lead: [
    "Conduct the daily huddle with the warehouse team - 7:00 AM",
    "Allocate staff for receiving, put-away, replenishment, and cycle counts",
    "Confirm the night shift handover is completed and reviewed",
    "Check that Warehouse TV/dashboard is on and displaying metrics - Every 2 Hours",
    "Inspect warehouse to ensure it is clean, organized, and safe before operations begin",
    "Ensure aisles are clear and nothing is stored on the floor - Every two hours",
    "Verify bin locations are correctly labelled - Sample 10 bins from each section",
    "Spot-check barcodes to ensure they are functioning correctly - Sample 5 per location",
    "Check that put-away adheres to FIFO/FEFO and storage rules - Sample 5 products per section",
    "Check that temperature-sensitive items are stored in correct zones - Every two hours",
    "Confirm replenishment activities do not block aisles or picking paths - Every two hours",
    "Ensure daily cycle counts are completed - Check every EOD",
    "Perform random spot checks to verify bin accuracy - Sample 5 products per section",
    "Ensure two weeks worth of Packaging Material at Regen",
    "Ensure no products have invalid or missing expiry dates - Check app every EOD",
    "Align with Packing Lead on stock availability, shortages, and priorities - Morning & EOD",
    "Share critical updates with Dispatch and Customer Service teams - Every two hours",
    "Ensure warehouse is clean, organized, and operationally ready for next shift",
    "Produce Grading Tracker completion checks - EOD",
    "Plan resources and staffing for the next day",
    "Check that warehouse assistants daily checklists are completed and signed off",
  ],
  night_shift_lead: [
    "Night shift team briefed and roles assigned",
    "Previous shift handover reviewed and acknowledged",
    "Pending put-away from day shift reviewed",
    "All night shift activities logged and documented",
    "Temperature checks completed for all cold storage areas",
    "Security walkthrough completed",
    "Incident log updated",
    "Morning shift handover prepared and ready",
  ],
  put_away_supervisor: [
    "All received products scheduled for put away reviewed",
    "Put-away team briefed and tasks assigned",
    "FIFO/FEFO compliance verified during put-away",
    "Bin locations verified before put-away",
    "All products put away within target time",
    "Pending put away quantity recorded",
    "Discrepancies during put-away reported",
    "Shift completion report submitted",
  ],
};
